---
version: '3.8'
# One may either build from a public git repo or a local repo

services:
    gateway:
        #build: https://github.com/leroleroinc/mvc-gateway.git
        build: ../../mvc-gateway
        ports:
            - 8080:8080
    adverbs:
        #build: https://github.com/leroleroinc/mvc-adverbs.git
        build: ../../mvc-adverbs
        ports:
            - 8081:8081
        depends_on:
            - database
            - discovery
            - cache
    verbs:
        #build: https://github.com/leroleroinc/mvc-verbs.git
        build: ../../mvc-verbs
        ports:
            - 8082:8082
        depends_on:
            - database
            - discovery
            - cache
    nouns:
        #build: https://github.com/leroleroinc/mvc-nouns.git
        build: ../../mvc-nouns
        ports:
            - 8083:8083
        depends_on:
            - database
            - discovery
            - cache
    database:
        #build: https://github.com/leroleroinc/database.git
        build: ../../database
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_DATABASE: lerolero
    discovery:
        #build: https://github.com/leroleroinc/mvc-discovery.git
        build: ../../mvc-discovery
        ports:
            - 8761:8761
    cache:
        image: redis:7.0-alpine
        ports:
            - 6379:6379
