---
version: '3.8'
# One may either build from a public git repo or a local repo

services:
    gateway:
        #build: https://github.com/leroleroinc/event-gateway.git
        build: ../../event-gateway
        ports:
            - 8080:8080
    adverbs:
        #build: https://github.com/leroleroinc/event-adverbs.git
        build: ../../event-adverbs
        #ports:
        #    - 8081:8081
        depends_on:
            - database
            - discovery
            - cache
            - kafka
    verbs:
        #build: https://github.com/leroleroinc/event-verbs.git
        build: ../../event-verbs
        #ports:
        #    - 8082:8082
        depends_on:
            - database
            - discovery
            - cache
            - kafka
    nouns:
        #build: https://github.com/leroleroinc/event-nouns.git
        build: ../../event-nouns
        #ports:
        #    - 8083:8083
        depends_on:
            - database
            - discovery
            - cache
            - kafka
    database:
        #build: https://github.com/leroleroinc/database.git
        build: ../../database
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_DATABASE: lerolero
    discovery:
        #build: https://github.com/leroleroinc/flux-discovery.git
        build: ../../flux-discovery
        ports:
            - 8761:8761
    cache:
        image: redis:7.0-alpine
        ports:
            - 6379:6379
    zookeeper:
         image: confluentinc/cp-zookeeper:latest
         environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
         ports:
            - 2181:2181
    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        ports:
            - 29092:29092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
